"""Lean proof → markdown demo conversion.

Converts .lean artifact files into markdown with Lean playground links.
No LLM needed — deterministic string formatting + LZ-string compression.

Used for: proof artifact type.
"""

import lzstring


def lean_playground_url(lean_code: str) -> str:
    """Generate Lean playground URL with compressed code.

    Uses LZ-string compression for the codez= parameter.
    """
    lz = lzstring.LZString()
    compressed = lz.compressToEncodedURIComponent(lean_code)
    return f"https://live.lean-lang.org/#codez={compressed}"


def create_proof_markdown(
    artifact_id: str,
    lean_code: str,
    artifact,
) -> tuple[str, str]:
    """Create markdown for a Lean proof artifact.

    Args:
        artifact_id: The artifact ID.
        lean_code: Raw Lean 4 source code.
        artifact: ProofArtifact object with title/summary fields.

    Returns:
        (markdown_content, playground_url).
    """
    if artifact is None:
        raise ValueError(f"artifact must not be None for {artifact_id}")

    title = artifact.title or artifact_id

    # Generate playground URL
    playground_url = lean_playground_url(lean_code)

    md = f"""# {title}

> **[Run in Lean Playground]({playground_url})**

[![Open in Lean](https://img.shields.io/badge/Lean_4-Verify_Proof-blue?logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCI+PHBhdGggZmlsbD0id2hpdGUiIGQ9Ik0xMiAyTDIgMTloMjBMMTIgMnoiLz48L3N2Zz4=)]({playground_url})

---

"""
    if artifact.summary:
        md += f"## Summary\n\n{artifact.summary}\n\n"

    md += f"""## Lean Code

```lean
{lean_code}
```

---
*Generated by AI Inventor Pipeline*
"""
    return md, playground_url
